AWSTemplateFormatVersion: "2010-09-09"
Transform:
  - AWS::Serverless-2016-10-31

Description: >
  Root template for Cloud Resume Project. Orchestrates backend and website stacks.

Parameters:
  DomainName:
    Type: String
    Description: "Domain name for the website (e.g. example.com)"

  HostedZoneId:
    Type: String
    Description: "Route53 HostedZone ID for DomainName"

  CertificateArn:
    Type: String
    Description: "ACM certificate ARN in us-east-1 for CloudFront"

Resources:
  BackendStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: backend.yaml
      Parameters:
        DomainName: !Ref DomainName

  WebsiteStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: website.yaml
      Parameters:
        DomainName: !Ref DomainName
        HostedZoneId: !Ref HostedZoneId
        CertificateArn: !Ref CertificateArn

Outputs:
  # Example: Reading outputs from the backend stack
  DynamoDBTableName:
    Description: "DynamoDB table name from backend"
    Value: !GetAtt BackendStack.Outputs.DynamoDBTableName

  LambdaFunctionName:
    Description: "Lambda function name from backend"
    Value: !GetAtt BackendStack.Outputs.LambdaFunctionName

  # Example: Reading outputs from the website stack
  WebsiteURL:
    Description: "CloudFront domain from website stack"
    Value: !GetAtt WebsiteStack.Outputs.WebsiteURL

  WebsiteBucketName:
    Description: "S3 Bucket for website from website stack"
    Value: !GetAtt WebsiteStack.Outputs.S3BucketName
