AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Security Stack - AWS WAF, IPSet, or other advanced security resources

Parameters:
  DomainName:
    Type: String
    Description: "Domain name for reference"

Resources:
  # WAFv2 ACL for CloudFront
  CloudResumeWAF:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: "CloudResumeWAF"
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        MetricName: "CloudResumeWAF"
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
      Rules:
        - Name: "BlockBadIPs"
          Priority: 0
          Action:
            Block: {}
          Statement:
            IPSetReferenceStatement:
              Arn: !Ref BlacklistIPSet
          VisibilityConfig:
            MetricName: "BlockBadIPs"
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true

  BlacklistIPSet:
    Type: AWS::WAFv2::IPSet
    Properties:
      Name: "CloudResumeBadIPs"
      Scope: CLOUDFRONT
      IPAddressVersion: IPV4
      Addresses:
        - "203.0.113.0/24"

Outputs:
  WAFArn:
    Description: "ARN of the WAF WebACL"
    Value: !GetAtt CloudResumeWAF.Arn
