AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Backend stack for Cloud Resume - Lambda + DynamoDB + HTTP API

Parameters:
  TableName:
    Type: String
    Default: "ZiyaretciSayaci"
    Description: DynamoDB table name

  AllowedOrigin:
    Type: String
    Default: "*"
    Description: CORS Allowed Origin 

Resources:
  # DynamoDB Tablosu
  VisitorCountTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "visitorID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "visitorID"
          KeyType: "HASH"

  # Lambda için IAM Rolü
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-LambdaRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:PutItem
                Resource: !GetAtt VisitorCountTable.Arn

  # Lambda Fonksiyonu
  ResumeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-Lambda"
      Runtime: python3.9
      Handler: lambda_function.lambda_handler
      CodeUri: ../backend   # lambda_function.py, backend klasörü altında olsun
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
          ALLOWED_ORIGIN: !Ref AllowedOrigin
      Events:
        VisitorCountApi:
          Type: HttpApi
          Properties:
            Path: /visitorcount
            Method: GET
            ApiId: !Ref VisitorCountHttpApi

  # HTTP API Kaynağı
  VisitorCountHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowOrigins: 
          - !Ref AllowedOrigin
        AllowMethods:
          - GET
          - OPTIONS

Outputs:
  ApiEndpoint:
    Description: "HTTP API endpoint for /visitorcount"
    Value: !Sub "https://${VisitorCountHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  DynamoDBTableName:
    Description: "Name of the DynamoDB table"
    Value: !Ref VisitorCountTable
  LambdaFunctionName:
    Description: "Name of the Lambda function"
    Value: !Ref ResumeFunction
