AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Website Bucket Stack (S3 + OAI)

Parameters:
  DomainName:
    Type: String
    Description: "Domain name for the site"

Resources:
  # 1) S3 Bucket
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${DomainName}-website-bucket"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true

  # 2) CloudFront OAI (artık bucket stack içinde)
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for Cloud Resume"

  # 3) Bucket Policy (OAI'ye GET izni veriyor)
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowCloudFrontOAI
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

Outputs:
  BucketName:
    Description: "Name of the S3 Bucket"
    Value: !Ref WebsiteBucket

  BucketRegionalDomainName:
    Description: "Regional Domain Name of the S3 Bucket"
    Value: !GetAtt WebsiteBucket.RegionalDomainName

  OaiCanonicalUserId:
    Description: "CloudFront OAI S3CanonicalUserId"
    Value: !GetAtt CloudFrontOAI.S3CanonicalUserId
