AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Website CloudFront Stack - Creates CloudFront distribution and Route53 alias in us-east-1.

Parameters:
  DomainName:
    Type: String
    Description: "Domain name for the site (e.g. example.com)"
  
  HostedZoneId:
    Type: String
    Description: "Hosted zone ID of the domain"
  
  CertificateArn:
    Type: String
    Description: "ACM certificate ARN in us-east-1 for CloudFront HTTPS"
  
  BucketRegionalDomainName:
    Type: String
    Description: "S3 Bucket Regional Domain Name (output from the bucket stack)"

Resources:
  # CloudFront Origin Access Identity
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for Cloud Resume"

  # CloudFront Distribution
  WebsiteDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: "http2"
        DefaultRootObject: "index.html"
        Aliases:
          - !Ref DomainName
        Origins:
          - Id: "S3Origin"
            DomainName: !Ref BucketRegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"
        DefaultCacheBehavior:
          TargetOriginId: "S3Origin"
          ViewerProtocolPolicy: "redirect-to-https"
          AllowedMethods: ["GET", "HEAD"]
          CachedMethods: ["GET", "HEAD"]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

  # Route53 Alias Record for CloudFront
  WebsiteAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt WebsiteDistribution.DomainName
        HostedZoneId: !GetAtt WebsiteDistribution.HostedZoneId

Outputs:
  DistributionDomainName:
    Description: "CloudFront distribution domain"
    Value: !GetAtt WebsiteDistribution.DomainName
