name: Website CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy-website:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Sync website to S3
        run: |
          # S3 bucket name from CloudFormation output or secret
          aws s3 sync website s3://${{ secrets.S3_BUCKET_NAME }} \
            --delete \
            --exclude ".github/*"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CF_DISTRIBUTION_ID }} \
            --paths "/*"
